# Generated by Django 4.2.1 on 2023-08-06 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marksheet', models.CharField(max_length=255, null=True)),
                ('twelfth_marksheet', models.CharField(max_length=255, null=True)),
                ('aadhar_card', models.CharField(max_length=255, null=True)),
                ('alternative_card', models.CharField(max_length=255, null=True)),
                ('bank_passbook', models.CharField(max_length=255, null=True)),
                ('graduation', models.CharField(max_length=255, null=True)),
                ('post_graduation', models.CharField(max_length=255, null=True)),
                ('experience_certificate', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('mother_name', models.CharField(max_length=255, null=True)),
                ('email_address', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255, null=True)),
                ('alter_phone', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_qualification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_qualification_reverse', to='accounts.qualification')),
                ('tenth_qualification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenth_qualification_reverse', to='accounts.qualification')),
                ('twelfth_qualification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twelfth_qualification_reverse', to='accounts.qualification')),
                ('university_qualification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_qualification_reverse', to='accounts.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_address', models.BooleanField(null=True)),
                ('current_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='accounts.address')),
                ('permanent_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('salary', models.CharField(max_length=255, null=True)),
                ('total_year', models.CharField(max_length=255, null=True)),
                ('user_experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='document_upload',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdocuments'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='personal_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpersonaldetails'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='qualification_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userqualification'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
