# Generated by Django 4.2.1 on 2023-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
