# Generated by Django 4.2.1 on 2023-08-03 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marksheet', models.CharField(max_length=255)),
                ('tweltf_marksheet', models.CharField(max_length=255)),
                ('adahar_card', models.CharField(max_length=255)),
                ('alter_government_id', models.CharField(max_length=255)),
                ('bank_passbook', models.CharField(max_length=255)),
                ('graduation', models.CharField(max_length=255)),
                ('post_graduation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('alterphone', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_other_qualification', to='accounts.qualification')),
                ('tenth_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenth_qualification', to='accounts.qualification')),
                ('twelfth_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_twelfth_qualification', to='accounts.qualification')),
                ('university_qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_university_qualification', to='accounts.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same_address', models.BooleanField()),
                ('current_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='accounts.address')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('total_year', models.CharField(max_length=255)),
                ('user_experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='document_upload',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdocuments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='personal_details',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpersonaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='qualification_details',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='accounts.userqualification'),
            preserve_default=False,
        ),
    ]
