# Generated by Django 4.2.1 on 2023-08-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_qualification_userdocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='roll_no',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
