# Generated by Django 4.2.1 on 2023-08-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_qualification_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdocuments',
            old_name='adahar_card',
            new_name='aadhar_card',
        ),
        migrations.RenameField(
            model_name='userdocuments',
            old_name='alter_government_id',
            new_name='alternative_card',
        ),
        migrations.RenameField(
            model_name='userdocuments',
            old_name='tweltf_marksheet',
            new_name='twelfth_marksheet',
        ),
    ]
