# Generated by Django 4.2.1 on 2023-08-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_adahar_card_userdocuments_aadhar_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonaldetails',
            old_name='email',
            new_name='email_address',
        ),
    ]
