# Generated by Django 4.2.1 on 2023-08-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_email_userpersonaldetails_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='document_upload',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdocuments'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='personal_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userpersonaldetails'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='qualification_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userqualification'),
        ),
    ]
