# Generated by Django 4.2.1 on 2023-08-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonaldetails',
            old_name='alterphone',
            new_name='alter_phone',
        ),
    ]
