# Generated by Django 4.2.1 on 2023-08-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_alterphone_userpersonaldetails_alter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
