# Generated by Django 4.2.1 on 2023-08-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userpersonaldetails_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industryexperience',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industryexperience',
            name='industry_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industryexperience',
            name='salary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='industryexperience',
            name='total_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='board_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='current_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='permanent_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='same_address',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='aadhar_card',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='alternative_card',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='bank_passbook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='graduation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='post_graduation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='tenth_marksheet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='twelfth_marksheet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='alter_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonaldetails',
            name='phonenumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='other_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_other_qualification', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='tenth_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tenth_qualification', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='twelfth_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_twelfth_qualification', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='university_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_university_qualification', to='accounts.qualification'),
        ),
    ]
