# Generated by Django 4.2.1 on 2023-08-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_address_city_alter_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqualification',
            name='other_qualification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_qualification_reverse', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='tenth_qualification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenth_qualification_reverse', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='twelfth_qualification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twelfth_qualification_reverse', to='accounts.qualification'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='university_qualification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_qualification_reverse', to='accounts.qualification'),
        ),
    ]
