# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2023-07-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230731_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdousermodel',
            name='role',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wdousermodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wdousermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='wdousermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wdousermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wdousermodel',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
